"""Pydantic schemas for clinical trial data."""

from datetime import date
from enum import Enum

from pydantic import BaseModel, Field


class Provenance(str, Enum):
    """Source provenance for a field."""
    STRUCTURED = "structured"  # From API structured field
    LLM = "llm"  # Inferred/generated by LLM
    MANUAL = "manual"  # Manually defined
    OPENTARGETS = "opentargets"  # From OpenTargets API


class ConfidenceFlags(BaseModel):
    """Confidence indicators for a trial record."""
    needs_review: bool = Field(False, description="Whether this record needs manual review")
    review_reasons: list[str] = Field(default_factory=list, description="Reasons for review flag")


class Trial(BaseModel):
    """Normalized clinical trial record."""
    nct_id: str = Field(..., description="ClinicalTrials.gov identifier (NCT########)")
    title: str = Field(..., description="Official trial title")
    phase: str | None = Field(None, description="Trial phase")
    status: str = Field(..., description="Recruitment status")
    conditions: list[str] = Field(default_factory=list, description="Target diseases/indications")
    interventions: list[str] = Field(default_factory=list, description="Drugs/treatments being tested")
    molecular_targets: list[str] | None = Field(None, description="Molecular targets (if extractable)")
    sponsor: str = Field(..., description="Lead sponsor organization")
    collaborators: list[str] = Field(default_factory=list, description="Collaborating organizations")
    start_date: date | None = Field(None, description="Study start date")
    completion_date: date | None = Field(None, description="Expected/actual completion date")
    locations: list[str] = Field(default_factory=list, description="Study site countries")
    summary: str = Field("", description="Brief description")
    source_url: str = Field(..., description="URL to trial on ClinicalTrials.gov")
    confidence_flags: ConfidenceFlags = Field(default_factory=ConfidenceFlags)

    class Config:
        json_encoders = {
            date: lambda v: v.isoformat() if v else None
        }


class SearchTerm(BaseModel):
    """A search term with provenance tracking."""
    term: str = Field(..., description="The search term")
    provenance: Provenance = Field(..., description="Source of this term")
    confidence: float = Field(1.0, description="Confidence score 0-1")


class GapReviewResult(BaseModel):
    """Result from LLM gap review."""
    coverage_assessment: str = Field(..., description="Good or Gaps Detected")
    suggested_terms: list[str] = Field(default_factory=list, description="Additional search terms")
    reasoning: str = Field(..., description="Explanation of assessment")
