"""Pydantic schemas for clinical trial data."""

from datetime import date
from enum import Enum
from typing import Self

from pydantic import BaseModel, Field


class Provenance(str, Enum):
    """Source provenance for a field."""
    STRUCTURED = "structured"  # From API structured field
    LLM = "llm"  # Inferred/generated by LLM
    MANUAL = "manual"  # Manually defined
    OPENTARGETS = "opentargets"  # From OpenTargets API


class TrialPhase(str, Enum):
    """Valid clinical trial phases (matches ClinicalTrials.gov)."""
    EARLY_PHASE_1 = "Early Phase 1"
    PHASE_1 = "Phase 1"
    PHASE_1_2 = "Phase 1/Phase 2"
    PHASE_2 = "Phase 2"
    PHASE_2_3 = "Phase 2/Phase 3"
    PHASE_3 = "Phase 3"
    PHASE_4 = "Phase 4"
    NOT_APPLICABLE = "Not Applicable"

    @classmethod
    def from_api(cls, api_value: str) -> Self | None:
        """Convert API value (e.g., 'PHASE1', 'EARLY_PHASE1') to enum."""
        # Normalize: "PHASE1" -> "PHASE_1", "EARLY_PHASE1" -> "EARLY_PHASE_1"
        normalized = api_value.upper().replace(" ", "_")
        # Insert underscore before digits if missing (PHASE1 -> PHASE_1)
        for i in range(1, 5):
            normalized = normalized.replace(f"PHASE{i}", f"PHASE_{i}")
        # Handle NA -> NOT_APPLICABLE
        if normalized == "NA":
            normalized = "NOT_APPLICABLE"
        try:
            return cls[normalized]
        except KeyError:
            return None


class TrialStatus(str, Enum):
    """Valid trial recruitment statuses (matches ClinicalTrials.gov)."""
    NOT_YET_RECRUITING = "Not yet recruiting"
    RECRUITING = "Recruiting"
    ENROLLING_BY_INVITATION = "Enrolling by invitation"
    ACTIVE_NOT_RECRUITING = "Active, not recruiting"
    SUSPENDED = "Suspended"
    TERMINATED = "Terminated"
    COMPLETED = "Completed"
    WITHDRAWN = "Withdrawn"
    UNKNOWN = "Unknown status"

    @classmethod
    def from_api(cls, api_value: str) -> Self | None:
        """Convert API value (e.g., 'RECRUITING', 'ACTIVE_NOT_RECRUITING') to enum."""
        normalized = api_value.upper().replace(" ", "_")
        try:
            return cls[normalized]
        except KeyError:
            return None


class StudyType(str, Enum):
    """Type of clinical study."""
    INTERVENTIONAL = "Interventional"
    OBSERVATIONAL = "Observational"
    EXPANDED_ACCESS = "Expanded Access"

    @classmethod
    def from_api(cls, api_value: str) -> Self | None:
        """Convert API value to enum."""
        normalized = api_value.upper().replace(" ", "_")
        try:
            return cls[normalized]
        except KeyError:
            return None


class ConfidenceFlags(BaseModel):
    """Confidence indicators for a trial record."""
    needs_review: bool = Field(False, description="Whether this record needs manual review")
    review_reasons: list[str] = Field(default_factory=list, description="Reasons for review flag")


class Trial(BaseModel):
    """Normalized clinical trial record."""
    nct_id: str = Field(..., description="ClinicalTrials.gov identifier (NCT########)")
    title: str = Field(..., description="Official trial title")
    phase: str | None = Field(None, description="Trial phase")
    status: str = Field(..., description="Recruitment status")
    study_type: str | None = Field(None, description="Type of study (Interventional/Observational)")
    conditions: list[str] = Field(default_factory=list, description="Target diseases/indications")
    interventions: list[str] = Field(default_factory=list, description="Drugs/treatments being tested")
    molecular_targets: list[str] | None = Field(None, description="Molecular targets (if extractable)")
    sponsor: str = Field(..., description="Lead sponsor organization")
    collaborators: list[str] = Field(default_factory=list, description="Collaborating organizations")
    enrollment_count: int | None = Field(None, description="Target or actual enrollment count")
    start_date: date | None = Field(None, description="Study start date")
    completion_date: date | None = Field(None, description="Expected/actual completion date")
    locations: list[str] = Field(default_factory=list, description="Study site countries")
    summary: str = Field("", description="Brief description")
    source_url: str = Field(..., description="URL to trial on ClinicalTrials.gov")
    confidence_flags: ConfidenceFlags = Field(default_factory=ConfidenceFlags)

    class Config:
        json_encoders = {
            date: lambda v: v.isoformat() if v else None
        }


class SearchTerm(BaseModel):
    """A search term with provenance tracking."""
    term: str = Field(..., description="The search term")
    provenance: Provenance = Field(..., description="Source of this term")
    confidence: float = Field(1.0, description="Confidence score 0-1")


class GapReviewResult(BaseModel):
    """Result from LLM gap review."""
    coverage_assessment: str = Field(..., description="Good or Gaps Detected")
    suggested_terms: list[str] = Field(default_factory=list, description="Additional search terms")
    reasoning: str = Field(..., description="Explanation of assessment")
