"""Pydantic schemas for clinical trial data."""

from datetime import date
from enum import Enum
from typing import Self

from pydantic import BaseModel, Field


class Provenance(str, Enum):
    """Source provenance for a field."""
    STRUCTURED = "structured"  # From API structured field
    LLM = "llm"  # Inferred/generated by LLM
    MANUAL = "manual"  # Manually defined / programmatically generated


class TrialPhase(str, Enum):
    """Valid clinical trial phases (matches ClinicalTrials.gov)."""
    EARLY_PHASE_1 = "Early Phase 1"
    PHASE_1 = "Phase 1"
    PHASE_1_2 = "Phase 1/Phase 2"
    PHASE_2 = "Phase 2"
    PHASE_2_3 = "Phase 2/Phase 3"
    PHASE_3 = "Phase 3"
    PHASE_4 = "Phase 4"
    NOT_APPLICABLE = "Not Applicable"

    @classmethod
    def from_api(cls, api_value: str) -> Self | None:
        """Convert API value (e.g., 'PHASE1', 'EARLY_PHASE1') to enum."""
        # Normalize: "PHASE1" -> "PHASE_1", "EARLY_PHASE1" -> "EARLY_PHASE_1"
        normalized = api_value.upper().replace(" ", "_")
        # Insert underscore before digits if missing (PHASE1 -> PHASE_1)
        for i in range(1, 5):
            normalized = normalized.replace(f"PHASE{i}", f"PHASE_{i}")
        # Handle NA -> NOT_APPLICABLE
        if normalized == "NA":
            normalized = "NOT_APPLICABLE"
        try:
            return cls[normalized]
        except KeyError:
            return None


class TrialStatus(str, Enum):
    """Valid trial recruitment statuses (matches ClinicalTrials.gov)."""
    NOT_YET_RECRUITING = "Not yet recruiting"
    RECRUITING = "Recruiting"
    ENROLLING_BY_INVITATION = "Enrolling by invitation"
    ACTIVE_NOT_RECRUITING = "Active, not recruiting"
    SUSPENDED = "Suspended"
    TERMINATED = "Terminated"
    COMPLETED = "Completed"
    WITHDRAWN = "Withdrawn"
    UNKNOWN = "Unknown status"

    @classmethod
    def from_api(cls, api_value: str) -> Self | None:
        """Convert API value (e.g., 'RECRUITING', 'ACTIVE_NOT_RECRUITING') to enum."""
        normalized = api_value.upper().replace(" ", "_")
        try:
            return cls[normalized]
        except KeyError:
            return None


class StudyType(str, Enum):
    """Type of clinical study."""
    INTERVENTIONAL = "Interventional"
    OBSERVATIONAL = "Observational"
    EXPANDED_ACCESS = "Expanded Access"

    @classmethod
    def from_api(cls, api_value: str) -> Self | None:
        """Convert API value to enum."""
        normalized = api_value.upper().replace(" ", "_")
        try:
            return cls[normalized]
        except KeyError:
            return None


class ConfidenceFlags(BaseModel):
    """Confidence indicators for a trial record."""
    needs_review: bool = Field(False, description="Whether this record needs manual review")
    review_reasons: list[str] = Field(default_factory=list, description="Reasons for review flag")


class MatchLikelihood(str, Enum):
    """Match likelihood categories for patient-trial matching."""
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    EXCLUDED = "EXCLUDED"
    UNKNOWN = "UNKNOWN"


class EligibilityInfo(BaseModel):
    """Structured eligibility information from trial."""
    raw_text: str | None = Field(None, description="Raw eligibility criteria text")
    minimum_age: str | None = Field(None, description="Minimum age requirement (e.g., '18 Years')")
    maximum_age: str | None = Field(None, description="Maximum age requirement (e.g., '75 Years')")
    sex: str | None = Field(None, description="Sex requirement: ALL, MALE, FEMALE")
    accepts_healthy_volunteers: bool | None = Field(None, description="Whether trial accepts healthy volunteers")


class PatientProfile(BaseModel):
    """Patient information for trial matching."""
    # Structured fields (optional but helpful for filtering)
    age: int | None = Field(None, description="Patient age in years")
    sex: str | None = Field(None, description="Patient sex: 'male' or 'female'")
    cancer_type: str | None = Field(None, description="Primary cancer type (e.g., 'NSCLC')")
    biomarkers: list[str] = Field(default_factory=list, description="Biomarkers/mutations (e.g., ['KRAS G12C'])")
    
    # Free-text description (required - the rich patient context)
    description: str = Field(..., description="Free-text description of patient history, prior treatments, comorbidities, ECOG status, etc.")
    
    # Optional preferences
    phase_preference: list[str] | None = Field(None, description="Preferred trial phases")
    location_preference: list[str] | None = Field(None, description="Preferred trial locations/countries")
    
    # Enhanced clinical fields
    ecog_status: int | None = Field(None, ge=0, le=5, description="ECOG performance status (0-5)")
    pd_l1_status: str | None = Field(None, description="PD-L1 expression level")
    prior_therapies: list[str] = Field(default_factory=list, description="Prior treatment regimens")
    brain_mets_status: str | None = Field(None, description="Brain metastases: 'none', 'stable', 'active'")
    co_mutations: list[str] = Field(default_factory=list, description="Co-mutations (STK11, KEAP1, etc.)")
    country: str | None = Field(None, description="Patient country for location matching")


class FilterResult(BaseModel):
    """Result of Stage 1 deterministic filtering."""
    passed: bool = Field(..., description="Whether trial passed the filter")
    excluded_reason: str | None = Field(None, description="Reason for exclusion if not passed")


class MatchResult(BaseModel):
    """Result of patient-trial matching."""
    nct_id: str = Field(..., description="Trial NCT ID")
    title: str = Field(..., description="Trial title")
    sponsor: str = Field(..., description="Trial sponsor")
    phase: str | None = Field(None, description="Trial phase")
    status: str = Field(..., description="Trial status")
    
    # Matching results
    match_likelihood: MatchLikelihood = Field(..., description="Overall match likelihood")
    filter_stage: str = Field(..., description="Stage where result was determined: 'fast_filter' or 'llm_scored'")
    
    # Explanation (populated by LLM for scored trials)
    supporting_factors: list[str] = Field(default_factory=list, description="Reasons patient likely qualifies")
    conflicts: list[str] = Field(default_factory=list, description="Reasons patient may not qualify")
    uncertainties: list[str] = Field(default_factory=list, description="Criteria that need verification")
    confidence: float = Field(0.0, description="Confidence score 0-1")
    reasoning: str = Field("", description="Brief explanation of assessment")
    
    # For fast-filter exclusions
    excluded_reason: str | None = Field(None, description="Reason for exclusion in fast filter")


class Trial(BaseModel):
    """Normalized clinical trial record."""
    nct_id: str = Field(..., description="ClinicalTrials.gov identifier (NCT########)")
    title: str = Field(..., description="Official trial title")
    phase: str | None = Field(None, description="Trial phase")
    status: str = Field(..., description="Recruitment status")
    study_type: str | None = Field(None, description="Type of study (Interventional/Observational)")
    conditions: list[str] = Field(default_factory=list, description="Target diseases/indications")
    interventions: list[str] = Field(default_factory=list, description="Drugs/treatments being tested")
    molecular_targets: list[str] | None = Field(None, description="Molecular targets (if extractable)")
    sponsor: str = Field(..., description="Lead sponsor organization")
    collaborators: list[str] = Field(default_factory=list, description="Collaborating organizations")
    enrollment_count: int | None = Field(None, description="Target or actual enrollment count")
    start_date: date | None = Field(None, description="Study start date")
    completion_date: date | None = Field(None, description="Expected/actual completion date")
    locations: list[str] = Field(default_factory=list, description="Study site countries")
    summary: str = Field("", description="Brief description")
    source_url: str = Field(..., description="URL to trial on ClinicalTrials.gov")
    eligibility: EligibilityInfo = Field(default_factory=EligibilityInfo, description="Eligibility criteria")
    confidence_flags: ConfidenceFlags = Field(default_factory=ConfidenceFlags)

    class Config:
        json_encoders = {
            date: lambda v: v.isoformat() if v else None
        }


class SearchTerm(BaseModel):
    """A search term with provenance tracking."""
    term: str = Field(..., description="The search term")
    provenance: Provenance = Field(..., description="Source of this term")
    confidence: float = Field(1.0, description="Confidence score 0-1")


class GapReviewResult(BaseModel):
    """Result from LLM gap review."""
    coverage_assessment: str = Field(..., description="Good or Gaps Detected")
    suggested_terms: list[str] = Field(default_factory=list, description="Additional search terms")
    reasoning: str = Field(..., description="Explanation of assessment")
